### ISSUE TITLE
ARM image

### ISSUE THREAD

**Issue by p4PpS** [jgraph/docker-drawio#10]
Hello,

is it possible to get an ARM(v7) version of the (alpine) image? Building it on an raspberry pi works but is very slow and unhandy.

Thanks in advance

**Comment by Michaelpalacce** [comment]
Since there seems to be no resolution from the developer I created one myself.

It's essentially a copy from their debian one ( with some code to inject the latest tag ).

Docker Hub: https://hub.docker.com/repository/docker/stefangenov/diagrams

Git Repo: https://github.com/Michaelpalacce/Docker/tree/master/diagrams

I will try to keep it up to date, feel free to bump me with an issue if you want me to trigger a build.

**Comment by Michaelpalacce** [comment]
If jgraph want to build this themselves, feel free to get any code you want. Check out https://docs.docker.com/buildx/working-with-buildx/ on more information on how the docker buildx builder works.

If they do officially start supporting an arm image I will deprecate mine

**Comment by ashrafteleb** [comment]
@Michaelpalacce Thanks for the solution. It's now added to the official build
@p4PpS Please give it a try.
