### ISSUE TITLE
Support for SSL certificates supplier by user

### ISSUE THREAD

**Issue by davidjgraph** [jgraph/docker-drawio#43]
Maybe as simple as mapping in path to key, but needs a security review.

**Comment by RussellNS** [comment]
I haven't gone through the steps yet, but I think this issue was answered in #13 "How to use self-provided SSL certificate."

I have the same issue, btw, and plan on trying these steps outside of work hours.

**Comment by davidjgraph** [comment]
The idea with this ticket is to allow the container to reference the cert outside the container so the docker can be used as-is.

**Comment by RussellNS** [comment]
My apologies, I'm only now seeing that you, the person that answered the issue in #13, are the same person opening this issue.  It's not my first "oops" moment, so I'll take my lumps.

That said, I think I've gotten close to what you were intending with this ticket.  These are the steps that I used to get there.  I doubt these are the final steps you'll settle on, but this works for me, and may accelerate you to your end result.

1. Use certbot to get a Let's Encrypt cert (assume domain 'draw.example.com').
2. Run docker-drawio container using the 'docker-compose.yml' file provided on your repo ('jgraph/docker-drawio').
3. Copy the 'server.xml' out of the docker-drawio container.
4. Stop the docker-drawio container.
5. In the local copy (not the container copy) of the 'server.xml', delete the comment tags ('<--' and '<!--') for the section containing '<Connector port="8443" protocol="org.apache.coyote.http11.Http11AprProtocol"'.
6. Update the 'docker-compose.yml' file to include volume mappings:

    volumes:
      \- ./server.xml:/usr/local/tomcat/conf/server.xml:ro
      \- /path/to/cert/cert.pem:/usr/local/tomcat/conf/localhost-rsa-cert.pem:ro
      \- /path/to/cert/privkey.pem:/usr/local/tomcat/conf/localhost-rsa-key.pem:ro
      \- /path/to/cert/fullchain.pem:/usr/local/tomcat/conf/localhost-rsa-chain.pem:ro

7. Run docker-drawio container using the updated 'docker-compose.yml' file.
8. Open web browser and navigate to 'https://draw.example.com:8443'.
9. Profit.

Sorry for the cruddy formatting.  However, this works with these notable attributes:

- Uses LE certs outside the container
- Skips the overhead of converting certs to a Java keystore
- Has the bare minimum (I think) of updating to the 'server.xml' file

I will also say to get this running, I had to verify that these dependencies were already installed in the docker-drawio container ([coped and pasted from the tomcat 8 docs](https://tomcat.apache.org/tomcat-8.0-doc/apr.html)):

- APR 1.2+ development headers (libapr1-dev package)
- OpenSSL 0.9.7+ development headers (libssl-dev package)
- JNI headers from Java compatible JDK 1.4+
- GNU development environment (gcc, make)

I'm only posting this since the readme at the main drawio GitHub site states that dependency tracking is why the drawio is closed to contributions, and if you develop in this direction, you'll definitely want to know these are dependencies for this to work.

I hope this is helpful.

**Comment by davidjgraph** [comment]
We already have built-in support for Let's Encrypt, see the README https://github.com/jgraph/docker-drawio. Did you find that wasn't working or lacked something?

The idea of this issue was more if user have an existing cert that they wanted to use.

**Comment by RussellNS** [comment]
Your implementation for LE is probably fine.  However, where I'm at, port 80 isn't freely allowed back in.  It is allowed in, but not in a way that the docker-drawio container could consume it.  In short, my use case is that of a user supplying my own SSL certificates that just so happens to be from Let's Encrypt.

Regardless, replacing step 1 for certs provided by a different CA, the steps should be largely the same?

**Comment by davidjgraph** [comment]
OK, cool. I'll try to take a proper read 8-).

**Comment by davidjgraph** [comment]
Closing since it's my issue and nobody seems to care.
